import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, BellRing, CalendarClock, CircleDollarSign, Settings2 } from "lucide-react";
import { money } from "@/lib/finance";
import type { CustomerDashboard, WidgetId } from "@/types/customer";

const labels: Record<WidgetId,string> = { actions:"Central de ações",safe_spend:"Quanto posso gastar?",cashflow:"Previsão de caixa",comparison:"Comparação mensal",subscriptions:"Assinaturas" };
function change(current: string, previous: string) {
  const now = Number(current), before = Number(previous);
  if (!Number.isFinite(now) || !Number.isFinite(before) || before === 0) return null;
  return ((now-before)/Math.abs(before)*100).toLocaleString("pt-BR",{maximumFractionDigits:1});
}
export function CustomerValueDashboard({ data, widgets, month }: { data: CustomerDashboard; widgets: WidgetId[]; month: string }) {
  const sections: Record<WidgetId,React.ReactNode> = {
    actions: <section className="panel value-panel" key="actions"><div className="section-heading"><div><span className="eyebrow blue">PRÓXIMO PASSO</span><h2>Central de ações</h2></div><BellRing size={22}/></div>{data.actions.length?<ul className="action-center">{data.actions.map((item)=><li key={item.kind}><div><strong>{item.title}</strong><small>{item.count} item(ns) · {money(item.amount)}</small></div><Link className="text-link" href={item.href}>Resolver</Link></li>)}</ul>:<p className="muted">Tudo em dia com base nos registros atuais.</p>}</section>,
    safe_spend: <section className="panel value-panel safe-spend" key="safe"><div className="section-heading"><div><span className="eyebrow blue">DECISÃO DE HOJE</span><h2>Quanto posso gastar?</h2></div><CircleDollarSign size={23}/></div><strong className="value-number">{money(data.safe_to_spend)}</strong><p>Saldo + entradas dos próximos 30 dias − compromissos − orçamento ainda reservado.</p><details><summary>Ver cálculo</summary><dl className="compact-totals"><div><dt>Saldo atual</dt><dd>{money(data.safe_components.balance)}</dd></div><div><dt>Entradas em 30 dias</dt><dd>{money(data.safe_components.income_30d)}</dd></div><div><dt>Saídas em 30 dias</dt><dd>{money(data.safe_components.expense_30d)}</dd></div><div><dt>Reserva do orçamento</dt><dd>{money(data.safe_components.budget_reserve)}</dd></div></dl></details></section>,
    cashflow: <section className="panel value-panel" key="cashflow"><div className="section-heading"><div><span className="eyebrow blue">OLHAR À FRENTE</span><h2>Previsão de caixa</h2></div><CalendarClock size={23}/></div><div className="forecast-strip">{data.cashflow.map((point)=><div key={point.days}><span>Em {point.days} dias</span><strong>{money(point.projected)}</strong></div>)}</div><p className="field-hint">Considera somente lançamentos pendentes já registrados. Gere recorrências para incluí-las.</p></section>,
    comparison: <section className="panel value-panel" key="comparison"><div className="section-heading"><div><span className="eyebrow blue">MÊS CONTRA MÊS</span><h2>Comparação mensal</h2></div><Link href={`/app/relatorio?month=${month}`} className="text-link">Relatório</Link></div><div className="comparison-grid">{(["income","expense"] as const).map((kind)=>{const delta=change(data.comparison.current[kind],data.comparison.previous[kind]);return <div key={kind}><span>{kind==="income"?"Receitas":"Despesas"}</span><strong>{money(data.comparison.current[kind])}</strong><small>{delta===null?"Sem base anterior":<>{Number(delta.replace(",","."))>=0?<ArrowUpRight size={14}/>:<ArrowDownRight size={14}/>} {delta}% em relação ao mês anterior</>}</small></div>})}</div></section>,
    subscriptions: <section className="panel value-panel" key="subscriptions"><div className="section-heading"><div><span className="eyebrow blue">CUSTOS RECORRENTES</span><h2>Assinaturas</h2></div><Link href="/app/assinaturas" className="text-link">Gerenciar</Link></div>{data.subscriptions.length?<ul className="subscription-mini">{data.subscriptions.slice(0,4).map((item)=><li key={item.id}><div><strong>{item.description}</strong><small>{item.merchant_name||"Serviço"} · dia {item.due_day}</small></div><strong>{money(item.amount)}</strong></li>)}</ul>:<p className="muted">Cadastre serviços recorrentes para acompanhar renovações e custo mensal.</p>}</section>,
  };
  return <section className="customer-value"><div className="customer-value-title"><div><span className="eyebrow blue">PAINEL INTELIGENTE</span><h2>Seu dinheiro pede atenção aqui</h2></div><Link className="button secondary compact" href="/app/painel"><Settings2 size={16}/> Personalizar</Link></div><div className="value-grid">{widgets.map((id)=>sections[id])}</div><span className="sr-only">Indicadores ativos: {widgets.map((id)=>labels[id]).join(", ")}</span></section>;
}
