"use client";
import { useActionState, useState } from "react";
import { Upload } from "lucide-react";
import { importTransactions } from "@/app/actions/customer";
import { parseCsv, parseOfx } from "@/lib/imports";
import { formatDate, money } from "@/lib/finance";
import type { Account, Category } from "@/types/finance";
import type { ImportRow } from "@/types/customer";
import { SubmitButton } from "@/components/submit-button";
export function ImportForm({profileId,accounts,categories}:{profileId:string;accounts:Account[];categories:Category[]}) {
  const [state,action]=useActionState(importTransactions,{}),[rows,setRows]=useState<ImportRow[]>([]),[file,setFile]=useState(""),[format,setFormat]=useState<"csv"|"ofx">("csv"),[parseError,setParseError]=useState("");
  async function selected(value:File|null){setRows([]);setParseError("");if(!value)return;try{if(value.size>2_000_000)throw new Error("O arquivo deve ter no máximo 2 MB.");const extension=value.name.toLowerCase().endsWith(".ofx")?"ofx":"csv";const parsed=extension==="ofx"?parseOfx(await value.text()):parseCsv(await value.text());setFile(value.name);setFormat(extension);setRows(parsed)}catch(error){setParseError(error instanceof Error?error.message:"Não foi possível ler o arquivo.")}}
  return <form action={action} className="form-stack"><input type="hidden" name="financial_profile_id" value={profileId}/><input type="hidden" name="file_name" value={file}/><input type="hidden" name="source_format" value={format}/><input type="hidden" name="rows" value={JSON.stringify(rows)}/><label className="file-drop"><Upload size={26}/><span>Escolher extrato CSV ou OFX</span><small>Até 2 MB e 500 lançamentos. O arquivo bruto não é armazenado.</small><input type="file" accept=".csv,.ofx,text/csv,application/x-ofx" onChange={(event)=>selected(event.target.files?.[0]??null)}/></label>{parseError&&<p className="feedback error">{parseError}</p>}{rows.length>0&&<><div className="form-grid"><label>Conta<select name="account_id" required defaultValue=""><option value="" disabled>Selecione</option>{accounts.map((a)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Categoria para receitas<select name="income_category_id" required defaultValue=""><option value="" disabled>Selecione</option>{categories.filter((c)=>c.kind==="income").map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Categoria para despesas<select name="expense_category_id" required defaultValue=""><option value="" disabled>Selecione</option>{categories.filter((c)=>c.kind==="expense").map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="import-summary"><strong>{rows.length} lançamentos encontrados</strong><span>{file}</span></div><div className="table-wrap"><table className="finance-table"><thead><tr><th>Data</th><th>Descrição</th><th>Tipo</th><th className="numeric">Valor</th></tr></thead><tbody>{rows.slice(0,20).map((row,index)=><tr key={`${row.date}-${index}`}><td>{formatDate(row.date)}</td><td>{row.description}</td><td>{row.type==="income"?"Receita":"Despesa"}</td><td className={`numeric amount-${row.type}`}>{money(row.amount)}</td></tr>)}</tbody></table></div>{rows.length>20&&<p className="field-hint">Prévia das primeiras 20 linhas.</p>}<label className="confirmation-check"><input type="checkbox" name="confirmed" value="yes" required/>Revisei a prévia e confirmo a importação.</label></>}{state.error&&<p className="feedback error">{state.error}</p>}{state.success&&<p className="feedback success">{state.success}</p>}<SubmitButton pendingLabel="Importando…">Importar lançamentos</SubmitButton></form>;
}
