export type PositionKind = "goal" | "reserve" | "investment";
export type Card = {
  id: string;
  financial_profile_id: string;
  name: string;
  institution: string;
  brand: string;
  last_four: string;
  credit_limit: string;
  closing_day: number;
  due_day: number;
  payment_account_id: string;
  color: string;
  active: boolean;
  used: string;
  available: string;
  utilization: string;
  current_invoice_id: string | null;
  current_month: string | null;
  current_total: string;
  due_on: string | null;
  invoice_status: string | null;
};
export type Invoice = {
  id: string | null;
  financial_profile_id?: string;
  card_id?: string;
  month: string;
  closes_on: string;
  due_on: string;
  paid_on: string | null;
  payment_account_name?: string | null;
  total: string;
  status: "open" | "closed" | "paid" | "overdue";
};
export type Position = {
  id: string;
  financial_profile_id: string;
  kind: PositionKind;
  name: string;
  description: string;
  institution: string;
  ticker: string;
  investment_type: string | null;
  target_amount: string | null;
  target_date: string | null;
  essential_cost: string | null;
  target_months: number | null;
  status: "active" | "completed" | "archived";
  created_at: string;
  current_value: string;
  deposited: string;
  withdrawn: string;
  result: string;
  return_percentage: string | null;
  target: string | null;
  progress: string | null;
  remaining: string;
  months_covered: string | null;
};
export type WorthItem = {
  id: string;
  financial_profile_id: string;
  name: string;
  kind: "asset" | "liability";
  category: string;
  amount: string;
  notes: string;
  active: boolean;
};
export type WorthTotals = {
  accounts: string;
  overdraft: string;
  investments: string;
  goals: string;
  reserves: string;
  goods: string;
  manual_debts: string;
  card_debt: string;
  assets: string;
  liabilities: string;
  net_worth: string;
};
export type WealthOverview = {
  cards: Card[];
  positions: Position[];
  net_worth: WorthTotals;
  items: WorthItem[];
  snapshots: { date: string; value: string }[];
  investment: {
    deposited: string;
    withdrawn: string;
    current_value: string;
    result: string;
    percentage: string | null;
  };
  allocation: { name: string; value: string }[];
  investment_history: { date: string; value: string }[];
  invoices_due: Invoice[];
  today: string;
};
export type CardDetail = {
  card: Card;
  invoice: Invoice;
  installments: {
    id: string;
    purchase_id: string;
    description: string;
    category_name: string;
    purchase_date: string;
    amount: string;
    purchase_total: string;
    number: number;
    count: number;
    cancelled: boolean;
    notes: string;
  }[];
};
export type PositionHistory = {
  rows: {
    id: string;
    kind: string;
    amount: string;
    delta: string;
    movement_date: string;
    notes: string;
    account_name: string | null;
  }[];
  total: number;
};
