import { ReportActions } from "@/components/customer/report-actions";
import { PeriodNav, PageHeading } from "@/components/finance/shared";
import { getDashboard } from "@/services/finance";
import { getInsights } from "@/services/insights";
import { getCustomerDashboard } from "@/services/customer";
import { getProfileContext } from "@/services/financial-profiles";
import { money, monthLabel, monthRange } from "@/lib/finance";
type SearchParams=Promise<Record<string,string|undefined>>;
export default async function Page({searchParams}:{searchParams:SearchParams}){const params=await searchParams,range=monthRange(params.month),[dashboard,insights,customer,profile]=await Promise.all([getDashboard(range.month),getInsights(range.month,"month"),getCustomerDashboard(range.month),getProfileContext()]);return <article className="report-page"><PageHeading title="Relatório mensal" description={`${profile.active?.name??"Perfil"} · ${monthLabel(range.month)}`}><ReportActions/></PageHeading><div className="period-row no-print"><PeriodNav month={range.month} path="/app/relatorio"/></div><section className="report-summary"><div><span>Receitas</span><strong>{money(dashboard.income)}</strong></div><div><span>Despesas</span><strong>{money(dashboard.expense)}</strong></div><div><span>Resultado</span><strong>{money(dashboard.result)}</strong></div><div><span>Saldo atual</span><strong>{money(dashboard.current_balance)}</strong></div></section>{customer&&<section className="panel report-section"><h2>Capacidade e previsão</h2><dl className="analysis-totals"><div><dt>Quanto posso gastar</dt><dd>{money(customer.data.safe_to_spend)}</dd></div>{customer.data.cashflow.map((point)=><div key={point.days}><dt>Saldo previsto em {point.days} dias</dt><dd>{money(point.projected)}</dd></div>)}</dl></section>}{insights&&<section className="panel report-section"><h2>Orçamento</h2><dl className="analysis-totals"><div><dt>Planejado</dt><dd>{money(insights.budget.planned)}</dd></div><div><dt>Realizado</dt><dd>{money(insights.budget.actual)}</dd></div><div><dt>Disponível</dt><dd>{money(insights.budget.remaining)}</dd></div></dl></section>}<section className="panel report-section"><h2>Despesas por categoria</h2>{dashboard.categories.length?<table className="finance-table"><thead><tr><th>Categoria</th><th>Participação</th><th className="numeric">Valor</th></tr></thead><tbody>{dashboard.categories.map((category)=><tr key={category.id}><td>{category.name}</td><td>{category.percentage.replace(".",",")}%</td><td className="numeric">{money(category.amount)}</td></tr>)}</tbody></table>:<p className="muted">Nenhuma despesa concluída neste mês.</p>}</section><footer className="report-footer">Gerado pelo iSev Finance em {new Intl.DateTimeFormat("pt-BR",{dateStyle:"long",timeZone:"America/Sao_Paulo"}).format(new Date())}. Valores baseados nos lançamentos registrados.</footer></article>}
