import { Building2, Clock3, Mail, Phone } from "lucide-react";
import { ContactForm, ReceivableForm } from "@/components/business/forms";
import { FinanceDialog } from "@/components/finance/forms";
import { EmptyState, PageHeading, ReadOnly } from "@/components/finance/shared";
import { getBusinessSuite } from "@/services/business";
import { getFinanceOptions } from "@/services/finance";
import { money } from "@/lib/finance";

const actionLabels: Record<string,string> = { insert: "Criou", update: "Atualizou", delete: "Excluiu", member_add: "Concedeu acesso", member_remove: "Removeu acesso" };
const entityLabels: Record<string,string> = { accounts: "conta", transaction_categories: "categoria", transactions: "lançamento", recurring_transactions: "recorrência", monthly_budgets: "orçamento", credit_cards: "cartão", credit_card_purchases: "compra", financial_positions: "posição", business_contacts: "contato", financial_profile_members: "membro" };
export default async function Page() {
  const [ctx, suite] = await Promise.all([getFinanceOptions(), getBusinessSuite()]);
  if (suite === null) return <EmptyState title="Recursos para empresas" description="Clientes, fornecedores e equipe ficam disponíveis quando o perfil financeiro é do tipo CNPJ." />;
  if (suite === undefined) return <EmptyState title="Recursos empresariais aguardando ativação" description="Aplique a migration empresarial depois de revisá-la." />;
  const write = ctx.role !== "viewer";
  return <><PageHeading title="Clientes e fornecedores" description="Centralize contatos, valores a receber e as mudanças importantes do perfil.">{write && ctx.ready && <><FinanceDialog label="Novo contato" title="Adicionar cliente ou fornecedor"><ContactForm profileId={ctx.profile.id}/></FinanceDialog><FinanceDialog primary label="Nova cobrança" title="Adicionar conta a receber"><ReceivableForm profileId={ctx.profile.id} contacts={suite.contacts} accounts={ctx.accounts} categories={ctx.categories}/></FinanceDialog></>}</PageHeading>{!write && <ReadOnly/>}
    <section className="business-layout"><div><div className="section-heading"><div><span className="eyebrow">CARTEIRA</span><h2>Contatos</h2></div><span className="count-badge">{suite.contacts.length}</span></div>{suite.contacts.length ? <div className="contacts-grid">{suite.contacts.map((contact) => <article className="panel contact-card" key={contact.id}><span className={`status-badge ${contact.active ? "status-completed" : "status-cancelled"}`}>{contact.kind === "client" ? "Cliente" : contact.kind === "supplier" ? "Fornecedor" : "Cliente e fornecedor"}</span><Building2 size={22}/><h3>{contact.name}</h3>{contact.document && <p>{contact.document}</p>}{contact.email && <p><Mail size={15}/>{contact.email}</p>}{contact.phone && <p><Phone size={15}/>{contact.phone}</p>}{write && <FinanceDialog label="Editar" title="Editar contato"><ContactForm profileId={ctx.profile.id} contact={contact}/></FinanceDialog>}</article>)}</div> : <p className="muted">Nenhum cliente ou fornecedor cadastrado.</p>}</div>
      <aside className="panel activity-panel"><div className="section-heading"><div><span className="eyebrow">RASTREABILIDADE</span><h2>Atividade recente</h2></div><Clock3 size={20}/></div>{suite.activity.length ? <ol className="activity-list">{suite.activity.map((item) => <li key={item.id}><strong>{actionLabels[item.action] ?? item.action} {entityLabels[item.entity] ?? item.entity}</strong><span>{item.summary.label || item.summary.role || "Registro financeiro"}</span><time dateTime={item.created_at}>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Sao_Paulo"}).format(new Date(item.created_at))}</time></li>)}</ol> : <p className="muted">As próximas alterações aparecerão aqui.</p>}</aside></section>
    <section className="panel table-panel"><div className="section-heading"><div><span className="eyebrow">CONTAS A RECEBER</span><h2>Em aberto por cliente</h2></div></div>{suite.receivables.length ? <div className="table-scroll"><table><thead><tr><th>Cliente</th><th>Lançamentos</th><th>Próximo vencimento</th><th>Em aberto</th></tr></thead><tbody>{suite.receivables.map((row) => <tr key={row.id}><td><strong>{row.name}</strong></td><td>{row.items}</td><td>{new Intl.DateTimeFormat("pt-BR",{timeZone:"UTC"}).format(new Date(`${row.next_due}T00:00:00Z`))}</td><td>{money(row.total)}</td></tr>)}</tbody></table></div> : <p className="muted">Nenhuma cobrança pendente associada a clientes.</p>}</section></>;
}
